### ISSUE TITLE
file permission error

### ISSUE THREAD

**Issue by mgcyung** [mschuldt/backlight.el#1]
When run "backlight-inc", there is a file permission error "Opening output file: Permission denied, /sys/class/backlight/intel_backlight/brightness"

**Comment by shukryzablah** [comment]
Likely to be related: https://wiki.archlinux.org/index.php/backlight#ACPI

> By default, only root can change the brightness by this method. To allow users in the video group to change the brightness, a udev rule such as the following can be used:

```
/etc/udev/rules.d/backlight.rules

ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="acpi_video0", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
```

**Comment by mschuldt** [comment]
Notes about adding the udev rule added to readme. Thank you @mgcyung  and @shukryzablah.

Also added changes to display a message about this when the file write results in a permission is denied error.
